project:
  title: "Running nonadiabatic MD in Julia"

subtitle: "*A look under the hood of the NQCD packages*"

author: "Alex Spears"
date-format: "DD.MM.YYYY"
date: "12.06.2024"

toc: true
toc-depth: 1

execute: 
  freeze: auto

format: 
  revealjs: 
    slideNumber: true
    transition: fade
    controls: true
    progress: true
    aspectRatio: 16:9
    theme: [default, custom.scss]
    logo: images/logo.svg
    footer: "Running nonadiabatic MD in Julia"
    width: 1920
    height: 1080
    auto-animate: true
    preview-links: auto
   