%%{
    init: {
        'theme': 'base', 
        'themeVariables': { 
            'fontSize': '25px',
            'primaryColor': '#0B6E4F',
            'primaryBorderColor': '#14cb92',
            'primaryTextColor': '#fff',
            'fontFamily': 'Lexend'
        }
    }
}%%

graph LR
    I[Starting conditions] --> P[O/P/SDE Problem]
    F[Equations of motion] --> P
    SP[Simulation parameters] --> P
    K[Numerical integration method] --> s[solve command]
    P --> s
    s --> M[Ensemble processing] --> S
    s --> R[Ensemble reduction] --> S[Solution object]
    s <--> C[Callbacks] <--> S
    S --> O[Plotting interface]
    S --> OA[Reduced values]