%%{
    init: {
        'theme': 'base', 
        'themeVariables': { 
            'fontSize': '25px',
            'primaryColor': '#0B6E4F',
            'primaryBorderColor': '#14cb92',
            'primaryTextColor': '#fff',
            'tertiaryTextColor': '#000',
            'fontFamily': 'Lexend'
        }
    }
}%%

graph LR
    subgraph DifferentialEquations.jl
        U[ODE representation for\n DifferentialEquations.jl]
        U --> S[Solution\n object]
    end
    subgraph sg1 ["NQCDynamics.jl"]
        direction LR
        A[Atomic structure] --> U
        P[PES] --> U
        I[Initial conditions] --> U
        D[Method-specific\n ODE solver] --> U
    end
    subgraph sg2 ["NQCDynamics.jl"]
        direction LR
        S --> O[Final trajectory]
        S --> ER[Ensemble\n statistics]
        S --> CQ[Calculated\n quantities]
    end
    style sg1 fill:#fa9f42, stroke:black;
    style sg2 fill:#fa9f42, stroke:black;
    style DifferentialEquations.jl fill:#279af1, stroke:black;