%%{init: {'theme': 'default', 'themeVariables': { 'fontSize': '25px'}}}%%

graph LR
    I[Starting conditions] --> P[O/P/SDE Problem]
    F[Equations of motion] --> P
    SP[Simulation parameters] --> P